### ISSUE TITLE
FYI: You can also do this natively with grunt.config.set

### ISSUE THREAD

**Issue by redonkulus** [wilmoore/require-grunt-configs#2]
You can also use the `grunt.loadTasks` method to load config files as well. The config file is just a js file that uses the `grunt.config.set` method. This has worked out well for me in past projects.
## Example

Directory:

```
grunt/
    configs/
        jshint.js
```

Contents of jshint.js:

```
'use strict';
module.exports = function (grunt) {
    grunt.config.set('jshint', {
        options: {
            jshintrc: '.jshintrc'
        },
        all: [
            'Gruntfile.js',
            'assets/js/*.js',
        ]
    });
};
```

Gruntfile.js:

```
grunt.loadTasks('grunt/configs');
```

**Comment by wilmoore** [comment]
Yes, you are the second person to point this out. Thanks :+1: 

I've updated the readme to point to an example written by @cowboy:
https://github.com/wilmoore/require-grunt-configs#alternatives
